//! Lagrange selector structures for constraint evaluation.

use p3_circuit::CircuitBuilder;
use p3_circuit::symbolic::RowSelectorsTargets;
use p3_field::coset::TwoAdicMultiplicativeCoset;
use p3_field::{ExtensionField, TwoAdicField};

use crate::Target;

/// Circuit version of Lagrange selectors for AIR constraint evaluation.
#[derive(Clone, Debug)]
pub struct RecursiveLagrangeSelectors {
    /// Row selector targets (is_first_row, is_last_row, is_transition)
    pub row_selectors: RowSelectorsTargets,
    /// Inverse of the vanishing polynomial: 1 / Z_H(point)
    ///
    /// The vanishing polynomial Z_H(x) = x^n - 1 for a domain of size n.
    /// This inverse is used to compute the quotient polynomial evaluation.
    pub inv_vanishing: Target,
}

impl RecursiveLagrangeSelectors {
    /// Lagrange selectors and the vanishing inverse for a two-adic coset.
    ///
    /// With `u = point / shift` and `Z(u) = u^n - 1` over a domain of `n`
    /// points generated by `g`:
    /// `is_first_row = Z(u)/(u - 1)`, `is_last_row = Z(u)/(u - g^-1)`,
    /// `is_transition = u - g^-1`, `inv_vanishing = 1/Z(u)`.
    pub(crate) fn two_adic_at_point<Val, Challenge>(
        circuit: &mut CircuitBuilder<Challenge>,
        domain: &TwoAdicMultiplicativeCoset<Val>,
        point: Target,
    ) -> Self
    where
        Val: TwoAdicField,
        Challenge: ExtensionField<Val>,
    {
        let shift_inv = circuit.alloc_const(Challenge::from(domain.shift_inverse()), "shift_inv");
        let one = circuit.alloc_const(Challenge::ONE, "1");
        let subgroup_gen_inv = circuit.alloc_const(
            Challenge::from(domain.subgroup_generator().inverse()),
            "subgroup_gen_inv",
        );

        let unshifted_point = circuit.alloc_mul(shift_inv, point, "unshifted_point");
        let us_exp = circuit.exp_power_of_2(unshifted_point, domain.log_size());
        let z_h = circuit.alloc_sub(us_exp, one, "z_h");

        let us_minus_one = circuit.alloc_sub(unshifted_point, one, "us_minus_one");
        let us_minus_gen_inv =
            circuit.alloc_sub(unshifted_point, subgroup_gen_inv, "us_minus_gen_inv");

        Self {
            row_selectors: RowSelectorsTargets {
                is_first_row: circuit.alloc_div(z_h, us_minus_one, "is_first_row"),
                is_last_row: circuit.alloc_div(z_h, us_minus_gen_inv, "is_last_row"),
                is_transition: us_minus_gen_inv,
            },
            inv_vanishing: circuit.alloc_div(one, z_h, "inv_vanishing"),
        }
    }
}
