//! Batch STARK prover and verifier that unifies all circuit tables
//! into a single batched STARK proof using `p3-batch-stark`.

use alloc::boxed::Box;
use alloc::string::String;
use alloc::vec;
use alloc::vec::Vec;

use p3_air::{Air, BaseAir};
use p3_batch_stark::{BatchProof, StarkGenericConfig, StarkInstance, Val};
use p3_circuit::tables::Traces;
use p3_field::{BasedVectorSpace, Field, PrimeField};
use p3_matrix::dense::RowMajorMatrix;
use p3_uni_stark::{ProverConstraintFolder, SymbolicAirBuilder, VerifierConstraintFolder};
use thiserror::Error;
use tracing::instrument;

use crate::air::{AddAir, ConstAir, MulAir, PublicAir, WitnessAir};
use crate::config::StarkField;
use crate::field_params::ExtractBinomialW;
use crate::prover::{
    BatchTableInstance, DynamicAirEntry, NonPrimitiveManifestEntry, TablePacking, TableProver,
    transmute_traces,
};

#[repr(usize)]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum PrimitiveTable {
    Witness = 0,
    Const = 1,
    Public = 2,
    Add = 3,
    Mul = 4,
}

/// Number of primitive circuit tables included in the unified batch STARK proof.
pub const NUM_PRIMITIVE_TABLES: usize = PrimitiveTable::Mul as usize + 1;

/// Row counts wrapper with type-safe indexing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RowCounts([usize; NUM_PRIMITIVE_TABLES]);

impl RowCounts {
    /// Creates a new RowCounts with the given row counts for each table.
    pub const fn new(rows: [usize; NUM_PRIMITIVE_TABLES]) -> Self {
        Self(rows)
    }

    /// Gets the row count for a specific table.
    #[inline]
    pub const fn get(&self, t: PrimitiveTable) -> usize {
        self.0[t as usize]
    }
}

impl core::ops::Index<PrimitiveTable> for RowCounts {
    type Output = usize;
    fn index(&self, table: PrimitiveTable) -> &Self::Output {
        &self.0[table as usize]
    }
}

impl From<[usize; NUM_PRIMITIVE_TABLES]> for RowCounts {
    fn from(rows: [usize; NUM_PRIMITIVE_TABLES]) -> Self {
        Self(rows)
    }
}

/// Proof bundle and metadata for the unified batch STARK proof across all circuit tables.
pub struct BatchStarkProof<SC>
where
    SC: StarkGenericConfig,
{
    /// The core cryptographic proof generated by `p3-batch-stark`.
    pub proof: BatchProof<SC>,
    /// Packing configuration used for the Add and Mul tables.
    pub table_packing: TablePacking,
    /// The number of rows in each of the circuit tables.
    pub rows: RowCounts,
    /// The degree of the field extension (`D`) used for the proof.
    pub ext_degree: usize,
    /// The binomial coefficient `W` for extension field multiplication, if `ext_degree > 1`.
    pub w_binomial: Option<Val<SC>>,
    /// Manifest describing dynamically batched non-primitive tables.
    pub non_primitives: Vec<NonPrimitiveManifestEntry<SC>>,
}

impl<SC> core::fmt::Debug for BatchStarkProof<SC>
where
    SC: StarkGenericConfig,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("BatchStarkProof")
            .field("table_packing", &self.table_packing)
            .field("rows", &self.rows)
            .field("ext_degree", &self.ext_degree)
            .field("w_binomial", &self.w_binomial)
            .finish()
    }
}

/// Produces a single batch STARK proof covering all circuit tables.
pub struct BatchStarkProver<SC>
where
    SC: StarkGenericConfig + 'static,
{
    config: SC,
    table_packing: TablePacking,
    /// Registered dynamic non-primitive table provers.
    non_primitive_provers: Vec<alloc::boxed::Box<dyn TableProver<SC>>>,
}

/// Errors for the batch STARK table prover.
#[derive(Debug, Error)]
pub enum BatchStarkProverError {
    #[error("unsupported extension degree: {0} (supported: 1,2,4,6,8)")]
    UnsupportedDegree(usize),

    #[error("missing binomial parameter W for extension-field multiplication")]
    MissingWForExtension,

    #[error("verification failed: {0}")]
    Verify(String),
}

/// Enum wrapper to allow heterogeneous table AIRs in a single batch STARK aggregation.
///
/// This enables different AIR types to be collected into a single vector for
/// batch STARK proving/verification while maintaining type safety.
enum CircuitTableAir<SC, const D: usize>
where
    SC: StarkGenericConfig,
{
    Witness(WitnessAir<Val<SC>, D>),
    Const(ConstAir<Val<SC>, D>),
    Public(PublicAir<Val<SC>, D>),
    Add(AddAir<Val<SC>, D>),
    Mul(MulAir<Val<SC>, D>),
    Dynamic(DynamicAirEntry<SC>),
}

impl<SC, const D: usize> BaseAir<Val<SC>> for CircuitTableAir<SC, D>
where
    SC: StarkGenericConfig,
{
    fn width(&self) -> usize {
        match self {
            Self::Witness(a) => a.width(),
            Self::Const(a) => a.width(),
            Self::Public(a) => a.width(),
            Self::Add(a) => a.width(),
            Self::Mul(a) => a.width(),
            Self::Dynamic(a) => a.air().width(),
        }
    }

    fn preprocessed_trace(&self) -> Option<RowMajorMatrix<Val<SC>>> {
        match self {
            Self::Witness(a) => a.preprocessed_trace(),
            Self::Const(a) => a.preprocessed_trace(),
            Self::Public(a) => a.preprocessed_trace(),
            Self::Add(a) => a.preprocessed_trace(),
            Self::Mul(a) => a.preprocessed_trace(),
            Self::Dynamic(a) => a.air().preprocessed_trace(),
        }
    }
}

impl<SC, const D: usize> Air<SymbolicAirBuilder<Val<SC>>> for CircuitTableAir<SC, D>
where
    SC: StarkGenericConfig,
    Val<SC>: PrimeField,
{
    fn eval(&self, builder: &mut SymbolicAirBuilder<Val<SC>>) {
        match self {
            Self::Witness(a) => a.eval(builder),
            Self::Const(a) => a.eval(builder),
            Self::Public(a) => a.eval(builder),
            Self::Add(a) => a.eval(builder),
            Self::Mul(a) => a.eval(builder),
            Self::Dynamic(a) => a.air().eval_symbolic(builder),
        }
    }
}

impl<'a, SC, const D: usize> Air<ProverConstraintFolder<'a, SC>> for CircuitTableAir<SC, D>
where
    SC: StarkGenericConfig,
    Val<SC>: PrimeField,
{
    fn eval(&self, builder: &mut ProverConstraintFolder<'a, SC>) {
        match self {
            Self::Witness(a) => a.eval(builder),
            Self::Const(a) => a.eval(builder),
            Self::Public(a) => a.eval(builder),
            Self::Add(a) => a.eval(builder),
            Self::Mul(a) => a.eval(builder),
            Self::Dynamic(a) => a.air().eval_prover(builder),
        }
    }
}

impl<'a, SC, const D: usize> Air<VerifierConstraintFolder<'a, SC>> for CircuitTableAir<SC, D>
where
    SC: StarkGenericConfig,
    Val<SC>: PrimeField,
{
    fn eval(&self, builder: &mut VerifierConstraintFolder<'a, SC>) {
        match self {
            Self::Witness(a) => a.eval(builder),
            Self::Const(a) => a.eval(builder),
            Self::Public(a) => a.eval(builder),
            Self::Add(a) => a.eval(builder),
            Self::Mul(a) => a.eval(builder),
            Self::Dynamic(a) => a.air().eval_verifier(builder),
        }
    }
}

impl<SC> BatchStarkProver<SC>
where
    SC: StarkGenericConfig + 'static,
    Val<SC>: StarkField,
{
    pub fn new(config: SC) -> Self {
        Self {
            config,
            table_packing: TablePacking::default(),
            non_primitive_provers: Vec::new(),
        }
    }

    #[must_use]
    pub fn with_table_packing(mut self, table_packing: TablePacking) -> Self {
        self.table_packing = table_packing;
        self
    }

    /// Register a dynamic non-primitive table prover.
    pub fn register_table_prover(&mut self, prover: Box<dyn TableProver<SC>>) {
        self.non_primitive_provers.push(prover);
    }

    /// Builder-style registration for a dynamic non-primitive table prover.
    #[must_use]
    pub fn with_table_prover(mut self, prover: Box<dyn TableProver<SC>>) -> Self {
        self.register_table_prover(prover);
        self
    }

    #[inline]
    pub const fn table_packing(&self) -> TablePacking {
        self.table_packing
    }

    /// Generate a unified batch STARK proof for all circuit tables.
    #[instrument(skip_all)]
    pub fn prove_all_tables<EF>(
        &self,
        traces: &Traces<EF>,
    ) -> Result<BatchStarkProof<SC>, BatchStarkProverError>
    where
        EF: Field + BasedVectorSpace<Val<SC>> + ExtractBinomialW<Val<SC>>,
    {
        let w_opt = EF::extract_w();
        match EF::DIMENSION {
            1 => self.prove::<EF, 1>(traces, None),
            2 => self.prove::<EF, 2>(traces, w_opt),
            4 => self.prove::<EF, 4>(traces, w_opt),
            6 => self.prove::<EF, 6>(traces, w_opt),
            8 => self.prove::<EF, 8>(traces, w_opt),
            d => Err(BatchStarkProverError::UnsupportedDegree(d)),
        }
    }

    /// Verify the unified batch STARK proof against all tables.
    pub fn verify_all_tables(
        &self,
        proof: &BatchStarkProof<SC>,
    ) -> Result<(), BatchStarkProverError> {
        match proof.ext_degree {
            1 => self.verify::<1>(proof, None),
            2 => self.verify::<2>(proof, proof.w_binomial),
            4 => self.verify::<4>(proof, proof.w_binomial),
            6 => self.verify::<6>(proof, proof.w_binomial),
            8 => self.verify::<8>(proof, proof.w_binomial),
            d => Err(BatchStarkProverError::UnsupportedDegree(d)),
        }
    }

    /// Generate a batch STARK proof for a specific extension field degree.
    ///
    /// This is the core proving logic that handles all circuit tables for a given
    /// extension field dimension. It constructs AIRs, converts traces to matrices,
    /// and generates the unified proof.
    fn prove<EF, const D: usize>(
        &self,
        traces: &Traces<EF>,
        w_binomial: Option<Val<SC>>,
    ) -> Result<BatchStarkProof<SC>, BatchStarkProverError>
    where
        EF: Field + BasedVectorSpace<Val<SC>> + BasedVectorSpace<Val<SC>>,
    {
        // TODO: Consider parallelizing AIR construction and trace-to-matrix conversions.
        // Build matrices and AIRs per table.
        let packing = self.table_packing;
        let add_lanes = packing.add_lanes();
        let mul_lanes = packing.mul_lanes();

        // Witness
        let witness_rows = traces.witness_trace.values.len();
        let witness_air = WitnessAir::<Val<SC>, D>::new(witness_rows);
        let witness_matrix: RowMajorMatrix<Val<SC>> =
            WitnessAir::<Val<SC>, D>::trace_to_matrix(&traces.witness_trace);

        // Const
        let const_rows = traces.const_trace.values.len();
        let const_air = ConstAir::<Val<SC>, D>::new(const_rows);
        let const_matrix: RowMajorMatrix<Val<SC>> =
            ConstAir::<Val<SC>, D>::trace_to_matrix(&traces.const_trace);

        // Public
        let public_rows = traces.public_trace.values.len();
        let public_air = PublicAir::<Val<SC>, D>::new(public_rows);
        let public_matrix: RowMajorMatrix<Val<SC>> =
            PublicAir::<Val<SC>, D>::trace_to_matrix(&traces.public_trace);

        // Add
        let add_rows = traces.add_trace.lhs_values.len();
        let add_air = AddAir::<Val<SC>, D>::new(add_rows, add_lanes);
        let add_matrix: RowMajorMatrix<Val<SC>> =
            AddAir::<Val<SC>, D>::trace_to_matrix(&traces.add_trace, add_lanes);

        // Mul
        let mul_rows = traces.mul_trace.lhs_values.len();
        let mul_air: MulAir<Val<SC>, D> = if D == 1 {
            MulAir::<Val<SC>, D>::new(mul_rows, mul_lanes)
        } else {
            let w = w_binomial.ok_or(BatchStarkProverError::MissingWForExtension)?;
            MulAir::<Val<SC>, D>::new_binomial(mul_rows, mul_lanes, w)
        };
        let mul_matrix: RowMajorMatrix<Val<SC>> =
            MulAir::<Val<SC>, D>::trace_to_matrix(&traces.mul_trace, mul_lanes);

        // We first handle all non-primitive tables dynamically, which will then be batched alongside primitive ones.

        let mut dynamic_instances: Vec<BatchTableInstance<SC>> = Vec::new();
        if D == 1 {
            let t: &Traces<Val<SC>> = unsafe { transmute_traces(traces) };
            for p in &self.non_primitive_provers {
                if let Some(instance) = p.batch_instance_d1(&self.config, packing, t) {
                    dynamic_instances.push(instance);
                }
            }
        } else if D == 2 {
            type EF2<F> = p3_field::extension::BinomialExtensionField<F, 2>;
            let t: &Traces<EF2<Val<SC>>> = unsafe { transmute_traces(traces) };
            for p in &self.non_primitive_provers {
                if let Some(instance) = p.batch_instance_d2(&self.config, packing, t) {
                    dynamic_instances.push(instance);
                }
            }
        } else if D == 4 {
            type EF4<F> = p3_field::extension::BinomialExtensionField<F, 4>;
            let t: &Traces<EF4<Val<SC>>> = unsafe { transmute_traces(traces) };
            for p in &self.non_primitive_provers {
                if let Some(instance) = p.batch_instance_d4(&self.config, packing, t) {
                    dynamic_instances.push(instance);
                }
            }
        } else if D == 6 {
            type EF6<F> = p3_field::extension::BinomialExtensionField<F, 6>;
            let t: &Traces<EF6<Val<SC>>> = unsafe { transmute_traces(traces) };
            for p in &self.non_primitive_provers {
                if let Some(instance) = p.batch_instance_d6(&self.config, packing, t) {
                    dynamic_instances.push(instance);
                }
            }
        } else if D == 8 {
            type EF8<F> = p3_field::extension::BinomialExtensionField<F, 8>;
            let t: &Traces<EF8<Val<SC>>> = unsafe { transmute_traces(traces) };
            for p in &self.non_primitive_provers {
                if let Some(instance) = p.batch_instance_d8(&self.config, packing, t) {
                    dynamic_instances.push(instance);
                }
            }
        }

        // Wrap AIRs in enum for heterogeneous batching and build instances in fixed order.
        let mut air_storage: Vec<CircuitTableAir<SC, D>> =
            Vec::with_capacity(NUM_PRIMITIVE_TABLES + dynamic_instances.len());
        let mut trace_storage: Vec<RowMajorMatrix<Val<SC>>> =
            Vec::with_capacity(NUM_PRIMITIVE_TABLES + dynamic_instances.len());
        let mut public_storage: Vec<Vec<Val<SC>>> =
            Vec::with_capacity(NUM_PRIMITIVE_TABLES + dynamic_instances.len());
        let mut manifest: Vec<NonPrimitiveManifestEntry<SC>> =
            Vec::with_capacity(dynamic_instances.len());

        // TODO: Support public values for tables

        air_storage.push(CircuitTableAir::Witness(witness_air));
        trace_storage.push(witness_matrix);
        public_storage.push(Vec::new());

        air_storage.push(CircuitTableAir::Const(const_air));
        trace_storage.push(const_matrix);
        public_storage.push(Vec::new());

        air_storage.push(CircuitTableAir::Public(public_air));
        trace_storage.push(public_matrix);
        public_storage.push(Vec::new());

        air_storage.push(CircuitTableAir::Add(add_air));
        trace_storage.push(add_matrix);
        public_storage.push(Vec::new());

        air_storage.push(CircuitTableAir::Mul(mul_air));
        trace_storage.push(mul_matrix);
        public_storage.push(Vec::new());

        for instance in dynamic_instances {
            let BatchTableInstance {
                id,
                air,
                trace,
                public_values,
                rows,
                data,
            } = instance;
            air_storage.push(CircuitTableAir::Dynamic(air));
            trace_storage.push(trace);
            public_storage.push(public_values.clone());
            manifest.push(NonPrimitiveManifestEntry {
                id,
                rows,
                public_values,
                data,
            });
        }

        let instances: Vec<StarkInstance<'_, SC, CircuitTableAir<SC, D>>> = air_storage
            .iter()
            .zip(trace_storage)
            .zip(public_storage)
            .map(|((air, trace), public_values)| StarkInstance {
                air,
                trace,
                public_values,
            })
            .collect();

        let proof = p3_batch_stark::prove_batch(&self.config, instances);

        Ok(BatchStarkProof {
            proof,
            table_packing: packing,
            rows: RowCounts::new([witness_rows, const_rows, public_rows, add_rows, mul_rows]),
            ext_degree: D,
            w_binomial: if D > 1 { w_binomial } else { None },
            non_primitives: manifest,
        })
    }

    /// Verify a batch STARK proof for a specific extension field degree.
    ///
    /// This reconstructs the AIRs from the proof metadata and verifies the proof
    /// against all circuit tables. The AIRs are reconstructed using the same
    /// configuration that was used during proof generation.
    fn verify<const D: usize>(
        &self,
        proof: &BatchStarkProof<SC>,
        w_binomial: Option<Val<SC>>,
    ) -> Result<(), BatchStarkProverError> {
        // Rebuild AIRs in the same order as prove.
        let packing = proof.table_packing;
        let add_lanes = packing.add_lanes();
        let mul_lanes = packing.mul_lanes();

        let witness_air = CircuitTableAir::Witness(WitnessAir::<Val<SC>, D>::new(
            proof.rows[PrimitiveTable::Witness],
        ));
        let const_air = CircuitTableAir::Const(ConstAir::<Val<SC>, D>::new(
            proof.rows[PrimitiveTable::Const],
        ));
        let public_air = CircuitTableAir::Public(PublicAir::<Val<SC>, D>::new(
            proof.rows[PrimitiveTable::Public],
        ));
        let add_air = CircuitTableAir::Add(AddAir::<Val<SC>, D>::new(
            proof.rows[PrimitiveTable::Add],
            add_lanes,
        ));
        let mul_air: CircuitTableAir<SC, D> = if D == 1 {
            CircuitTableAir::Mul(MulAir::<Val<SC>, D>::new(
                proof.rows[PrimitiveTable::Mul],
                mul_lanes,
            ))
        } else {
            let w = w_binomial.ok_or(BatchStarkProverError::MissingWForExtension)?;
            CircuitTableAir::Mul(MulAir::<Val<SC>, D>::new_binomial(
                proof.rows[PrimitiveTable::Mul],
                mul_lanes,
                w,
            ))
        };
        let mut airs = vec![witness_air, const_air, public_air, add_air, mul_air];
        // TODO: Handle public values.
        let mut pvs: Vec<Vec<Val<SC>>> = vec![Vec::new(); NUM_PRIMITIVE_TABLES];

        for entry in &proof.non_primitives {
            let plugin = self
                .non_primitive_provers
                .iter()
                .find(|p| {
                    let tp = p.as_ref();
                    TableProver::id(tp) == entry.id
                })
                .ok_or_else(|| {
                    BatchStarkProverError::Verify(alloc::format!(
                        "unknown non-primitive plugin: {}",
                        entry.id
                    ))
                })?;
            let air = plugin
                .batch_air_from_manifest(&self.config, D, entry)
                .map_err(BatchStarkProverError::Verify)?;
            airs.push(CircuitTableAir::Dynamic(air));
            pvs.push(entry.public_values.clone());
        }

        p3_batch_stark::verify_batch(&self.config, &airs, &proof.proof, &pvs)
            .map_err(|e| BatchStarkProverError::Verify(alloc::format!("{e:?}")))
    }
}

#[cfg(test)]
mod tests {
    use p3_baby_bear::BabyBear;
    use p3_circuit::builder::CircuitBuilder;
    use p3_field::PrimeCharacteristicRing;
    use p3_field::extension::BinomialExtensionField;
    use p3_goldilocks::Goldilocks;
    use p3_koala_bear::KoalaBear;

    use super::*;
    use crate::config;

    #[test]
    fn test_babybear_batch_stark_base_field() {
        let mut builder = CircuitBuilder::<BabyBear>::new();

        // x + 5*2 - 3 + (-1) == expected
        let x = builder.add_public_input();
        let expected = builder.add_public_input();
        let c5 = builder.add_const(BabyBear::from_u64(5));
        let c2 = builder.add_const(BabyBear::from_u64(2));
        let c3 = builder.add_const(BabyBear::from_u64(3));
        let neg_one = builder.add_const(BabyBear::NEG_ONE);

        let mul_result = builder.mul(c5, c2); // 10
        let add_result = builder.add(x, mul_result); // x + 10
        let sub_result = builder.sub(add_result, c3); // x + 7
        let final_result = builder.add(sub_result, neg_one); // x + 6

        let diff = builder.sub(final_result, expected);
        builder.assert_zero(diff);

        let circuit = builder.build().unwrap();
        let mut runner = circuit.runner();

        let x_val = BabyBear::from_u64(7);
        let expected_val = BabyBear::from_u64(13); // 7 + 10 - 3 - 1 = 13
        runner.set_public_inputs(&[x_val, expected_val]).unwrap();
        let traces = runner.run().unwrap();

        let cfg = config::baby_bear().build();
        let prover = BatchStarkProver::new(cfg);
        let proof = prover.prove_all_tables(&traces).unwrap();
        assert_eq!(proof.ext_degree, 1);
        assert!(proof.w_binomial.is_none());
        prover.verify_all_tables(&proof).unwrap();
    }

    #[test]
    fn test_extension_field_batch_stark() {
        type Ext4 = BinomialExtensionField<BabyBear, 4>;
        let mut builder = CircuitBuilder::<Ext4>::new();
        let x = builder.add_public_input();
        let y = builder.add_public_input();
        let z = builder.add_public_input();
        let expected = builder.add_public_input();
        let xy = builder.mul(x, y);
        let res = builder.add(xy, z);
        let diff = builder.sub(res, expected);
        builder.assert_zero(diff);
        let circuit = builder.build().unwrap();
        let mut runner = circuit.runner();
        let xv = Ext4::from_basis_coefficients_slice(&[
            BabyBear::from_u64(2),
            BabyBear::from_u64(3),
            BabyBear::from_u64(5),
            BabyBear::from_u64(7),
        ])
        .unwrap();
        let yv = Ext4::from_basis_coefficients_slice(&[
            BabyBear::from_u64(11),
            BabyBear::from_u64(13),
            BabyBear::from_u64(17),
            BabyBear::from_u64(19),
        ])
        .unwrap();
        let zv = Ext4::from_basis_coefficients_slice(&[
            BabyBear::from_u64(23),
            BabyBear::from_u64(29),
            BabyBear::from_u64(31),
            BabyBear::from_u64(37),
        ])
        .unwrap();
        let expected_v = xv * yv + zv;
        runner.set_public_inputs(&[xv, yv, zv, expected_v]).unwrap();
        let traces = runner.run().unwrap();

        let cfg = config::baby_bear().build();
        let prover = BatchStarkProver::new(cfg);
        let proof = prover.prove_all_tables(&traces).unwrap();
        assert_eq!(proof.ext_degree, 4);
        // Ensure W was captured
        let expected_w = <Ext4 as ExtractBinomialW<BabyBear>>::extract_w().unwrap();
        assert_eq!(proof.w_binomial, Some(expected_w));
        prover.verify_all_tables(&proof).unwrap();
    }

    #[test]
    fn test_koalabear_batch_stark_base_field() {
        let mut builder = CircuitBuilder::<KoalaBear>::new();

        // a * b + 100 - (-1) == expected
        let a = builder.add_public_input();
        let b = builder.add_public_input();
        let expected = builder.add_public_input();
        let c = builder.add_const(KoalaBear::from_u64(100));
        let d = builder.add_const(KoalaBear::NEG_ONE);

        let ab = builder.mul(a, b);
        let add = builder.add(ab, c);
        let final_res = builder.sub(add, d);
        let diff = builder.sub(final_res, expected);
        builder.assert_zero(diff);

        let circuit = builder.build().unwrap();
        let mut runner = circuit.runner();

        let a_val = KoalaBear::from_u64(42);
        let b_val = KoalaBear::from_u64(13);
        let expected_val = KoalaBear::from_u64(647); // 42*13 + 100 - (-1)
        runner
            .set_public_inputs(&[a_val, b_val, expected_val])
            .unwrap();
        let traces = runner.run().unwrap();

        let cfg = config::koala_bear().build();
        let prover = BatchStarkProver::new(cfg);
        let proof = prover.prove_all_tables(&traces).unwrap();
        assert_eq!(proof.ext_degree, 1);
        assert!(proof.w_binomial.is_none());
        prover.verify_all_tables(&proof).unwrap();
    }

    #[test]
    fn test_koalabear_batch_stark_extension_field_d8() {
        type KBExtField = BinomialExtensionField<KoalaBear, 8>;
        let mut builder = CircuitBuilder::<KBExtField>::new();

        // x * y * z == expected
        let x = builder.add_public_input();
        let y = builder.add_public_input();
        let expected = builder.add_public_input();
        let z = builder.add_const(
            KBExtField::from_basis_coefficients_slice(&[
                KoalaBear::from_u64(1),
                KoalaBear::NEG_ONE,
                KoalaBear::from_u64(2),
                KoalaBear::from_u64(3),
                KoalaBear::from_u64(4),
                KoalaBear::from_u64(5),
                KoalaBear::from_u64(6),
                KoalaBear::from_u64(7),
            ])
            .unwrap(),
        );

        let xy = builder.mul(x, y);
        let xyz = builder.mul(xy, z);
        let diff = builder.sub(xyz, expected);
        builder.assert_zero(diff);

        let circuit = builder.build().unwrap();
        let mut runner = circuit.runner();

        let x_val = KBExtField::from_basis_coefficients_slice(&[
            KoalaBear::from_u64(4),
            KoalaBear::from_u64(6),
            KoalaBear::from_u64(8),
            KoalaBear::from_u64(10),
            KoalaBear::from_u64(12),
            KoalaBear::from_u64(14),
            KoalaBear::from_u64(16),
            KoalaBear::from_u64(18),
        ])
        .unwrap();
        let y_val = KBExtField::from_basis_coefficients_slice(&[
            KoalaBear::from_u64(12),
            KoalaBear::from_u64(14),
            KoalaBear::from_u64(16),
            KoalaBear::from_u64(18),
            KoalaBear::from_u64(20),
            KoalaBear::from_u64(22),
            KoalaBear::from_u64(24),
            KoalaBear::from_u64(26),
        ])
        .unwrap();
        let z_val = KBExtField::from_basis_coefficients_slice(&[
            KoalaBear::from_u64(1),
            KoalaBear::NEG_ONE,
            KoalaBear::from_u64(2),
            KoalaBear::from_u64(3),
            KoalaBear::from_u64(4),
            KoalaBear::from_u64(5),
            KoalaBear::from_u64(6),
            KoalaBear::from_u64(7),
        ])
        .unwrap();

        let expected_val = x_val * y_val * z_val;
        runner
            .set_public_inputs(&[x_val, y_val, expected_val])
            .unwrap();
        let traces = runner.run().unwrap();

        let cfg = config::koala_bear().build();
        let prover = BatchStarkProver::new(cfg);
        let proof = prover.prove_all_tables(&traces).unwrap();
        assert_eq!(proof.ext_degree, 8);
        let expected_w = <KBExtField as ExtractBinomialW<KoalaBear>>::extract_w().unwrap();
        assert_eq!(proof.w_binomial, Some(expected_w));
        prover.verify_all_tables(&proof).unwrap();
    }

    #[test]
    fn test_goldilocks_batch_stark_extension_field_d2() {
        type Ext2 = BinomialExtensionField<Goldilocks, 2>;
        let mut builder = CircuitBuilder::<Ext2>::new();

        // x * y + z == expected
        let x = builder.add_public_input();
        let y = builder.add_public_input();
        let z = builder.add_public_input();
        let expected = builder.add_public_input();

        let xy = builder.mul(x, y);
        let res = builder.add(xy, z);
        let diff = builder.sub(res, expected);
        builder.assert_zero(diff);

        let circuit = builder.build().unwrap();
        let mut runner = circuit.runner();

        let x_val =
            Ext2::from_basis_coefficients_slice(&[Goldilocks::from_u64(3), Goldilocks::NEG_ONE])
                .unwrap();
        let y_val = Ext2::from_basis_coefficients_slice(&[
            Goldilocks::from_u64(7),
            Goldilocks::from_u64(11),
        ])
        .unwrap();
        let z_val = Ext2::from_basis_coefficients_slice(&[
            Goldilocks::from_u64(13),
            Goldilocks::from_u64(17),
        ])
        .unwrap();
        let expected_val = x_val * y_val + z_val;

        runner
            .set_public_inputs(&[x_val, y_val, z_val, expected_val])
            .unwrap();
        let traces = runner.run().unwrap();

        let cfg = config::goldilocks().build();
        let prover = BatchStarkProver::new(cfg);
        let proof = prover.prove_all_tables(&traces).unwrap();
        assert_eq!(proof.ext_degree, 2);
        let expected_w = <Ext2 as ExtractBinomialW<Goldilocks>>::extract_w().unwrap();
        assert_eq!(proof.w_binomial, Some(expected_w));
        prover.verify_all_tables(&proof).unwrap();
    }
}
