//! Batch STARK proof types and error definitions.

use alloc::vec::Vec;

use p3_batch_stark::{BatchProof, StarkGenericConfig, Val};
use p3_circuit::op::{NonPrimitiveOpType, PrimitiveOpType};
use thiserror::Error;

use super::NonPrimitiveTableEntry;
use super::packing::TablePacking;

pub type PrimitiveTable = PrimitiveOpType;

/// Number of primitive circuit tables included in the unified batch STARK proof.
pub const NUM_PRIMITIVE_TABLES: usize = PrimitiveTable::Mul as usize + 1;

/// Row counts wrapper with type-safe indexing.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RowCounts([usize; NUM_PRIMITIVE_TABLES]);

impl RowCounts {
    /// Creates a new RowCounts with the given row counts for each table.
    pub const fn new(rows: [usize; NUM_PRIMITIVE_TABLES]) -> Self {
        // Validate that all row counts are non-zero
        let mut i = 0;
        while i < rows.len() {
            assert!(rows[i] > 0);
            i += 1;
        }
        Self(rows)
    }

    /// Gets the row count for a specific table.
    #[inline]
    pub const fn get(&self, t: PrimitiveTable) -> usize {
        self.0[t as usize]
    }
}

impl core::ops::Index<PrimitiveTable> for RowCounts {
    type Output = usize;
    fn index(&self, table: PrimitiveTable) -> &Self::Output {
        &self.0[table as usize]
    }
}

impl From<[usize; NUM_PRIMITIVE_TABLES]> for RowCounts {
    fn from(rows: [usize; NUM_PRIMITIVE_TABLES]) -> Self {
        Self(rows)
    }
}

/// Proof bundle and metadata for the unified batch STARK proof across all circuit tables.
pub struct BatchStarkProof<SC>
where
    SC: StarkGenericConfig,
{
    /// The core cryptographic proof generated by `p3-batch-stark`.
    pub proof: BatchProof<SC>,
    /// Packing configuration used for the Witness, Add, and Mul tables.
    pub table_packing: TablePacking,
    /// The number of rows in each of the circuit tables.
    pub rows: RowCounts,
    /// The degree of the field extension (`D`) used for the proof.
    pub ext_degree: usize,
    /// The binomial coefficient `W` for extension field multiplication, if `ext_degree > 1`.
    pub w_binomial: Option<Val<SC>>,
    /// Manifest describing batched non-primitive tables defined at runtime.
    pub non_primitives: Vec<NonPrimitiveTableEntry<SC>>,
}

impl<SC> core::fmt::Debug for BatchStarkProof<SC>
where
    SC: StarkGenericConfig,
{
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("BatchStarkProof")
            .field("table_packing", &self.table_packing)
            .field("rows", &self.rows)
            .field("ext_degree", &self.ext_degree)
            .field("w_binomial", &self.w_binomial)
            .finish()
    }
}

/// Errors for the batch STARK table prover.
#[derive(Debug, Error)]
pub enum BatchStarkProverError {
    #[error("unsupported extension degree: {0} (supported: 1,2,4,6,8)")]
    UnsupportedDegree(usize),

    #[error("missing binomial parameter W for extension-field multiplication")]
    MissingWForExtension,

    #[error("verification failed: {0}")]
    Verify(alloc::string::String),

    #[error("missing table prover for non-primitive op `{0:?}`")]
    MissingTableProver(NonPrimitiveOpType),
}
